| **Function**            | **Description**              | **Syntax**                                               | **Example**                                    |


| **`length()`**          | Returns the length of a string.                                                                                           | `length(string)`                                         | `SELECT length('Hello, World!');` ➔ `13`                                         |                                 |                                       |
| **`lower()`**           | Converts a string to lowercase.                                                                                           | `lower(string)`                                          | `SELECT lower('HELLO');` ➔ `hello`                                               |                                 |                                       |
| **`upper()`**           | Converts a string to uppercase.                                                                                           | `upper(string)`                                          | `SELECT upper('hello');` ➔ `HELLO`                                               |                                 |                                       |
| **`trim()`**            | Removes leading and trailing spaces from a string.                                                                        | \`trim(\[LEADING                                         | TRAILING                                                                         | BOTH] characters FROM string)\` | `SELECT trim('  hello  ');` ➔ `hello` |
| **`ltrim()`**           | Removes leading spaces from a string.                                                                                     | `ltrim(string)`                                          | `SELECT ltrim('  hello');` ➔ `hello`                                             |                                 |                                       |
| **`rtrim()`**           | Removes trailing spaces from a string.                                                                                    | `rtrim(string)`                                          | `SELECT rtrim('hello  ');` ➔ `hello`                                             |                                 |                                       |
| **`substr()`**          | Extracts a substring from a string.                                                                                       | `substr(string, start, length)`                          | `SELECT substr('Hello, World!', 1, 5);` ➔ `Hello`                                |                                 |                                       |
| **`concat()`**          | Concatenates two or more strings.                                                                                         | `concat(string1, string2, ...)`                          | `SELECT concat('Hello', ' ', 'World');` ➔ `Hello World`                          |                                 |                                       |
| **`concat_ws()`**       | Concatenates strings with a separator.                                                                                    | `concat_ws(separator, string1, string2, ...)`            | `SELECT concat_ws('-', '2025', '05', '17');` ➔ `2025-05-17`                      |                                 |                                       |
| **`position()`**        | Returns the position of a substring within a string (1-based index).                                                      | `position(substring IN string)`                          | `SELECT position('World' IN 'Hello, World!');` ➔ `8`                             |                                 |                                       |
| **`replace()`**         | Replaces all occurrences of a substring with another string.                                                              | `replace(string, old_substring, new_substring)`          | `SELECT replace('Hello, World!', 'World', 'PostgreSQL');` ➔ `Hello, PostgreSQL!` |                                 |                                       |
| **`repeat()`**          | Repeats a string a specified number of times.                                                                             | `repeat(string, number)`                                 | `SELECT repeat('abc', 3);` ➔ `abcabcabc`                                         |                                 |                                       |
| **`reverse()`**         | Reverses a string.                                                                                                        | `reverse(string)`                                        | `SELECT reverse('hello');` ➔ `olleh`                                             |                                 |                                       |
| **`initcap()`**         | Capitalizes the first letter of each word in the string.                                                                  | `initcap(string)`                                        | `SELECT initcap('hello world');` ➔ `Hello World`                                 |                                 |                                       |
| **`char_length()`**     | Returns the number of characters in a string (equivalent to `length()` in some cases).                                    | `char_length(string)`                                    | `SELECT char_length('Hello');` ➔ `5`                                             |                                 |                                       |
| **`overlay()`**         | Replaces part of a string with another string.                                                                            | `overlay(string placing new_string from start_position)` | `SELECT overlay('hello' placing 'abc' from 2);` ➔ `habclo`                       |                                 |                                       |
| **`strpos()`**          | Returns the position of the first occurrence of a substring.                                                              | `strpos(string, substring)`                              | `SELECT strpos('Hello, World!', 'World');` ➔ `8`                                 |                                 |                                       |
| **`to_ascii()`**        | Converts a string to ASCII by removing non-ASCII characters.                                                              | `to_ascii(string)`                                       | `SELECT to_ascii('Héllo Wörld!');` ➔ `Hello World!`                              |                                 |                                       |
| **`string_agg()`**      | Aggregates a set of strings into one string, with an optional separator.                                                  | `string_agg(expression, separator)`                      | `SELECT string_agg(name, ', ') FROM students;`                                   |                                 |                                       |
| **`encode()`**          | Encodes a bytea value to a string using a specified encoding.                                                             | `encode(bytea, encoding)`                                | `SELECT encode('Hello'::bytea, 'base64');` ➔ `SGVsbG8=`                          |                                 |                                       |
| **`decode()`**          | Decodes a string from a specific encoding into a bytea value.                                                             | `decode(string, encoding)`                               | `SELECT decode('SGVsbG8=', 'base64');` ➔ `Hello`                                 |                                 |                                       |
| **`left()`**            | Returns the first N characters of a string.                                                                               | `left(string, N)`                                        | `SELECT left('Hello, World!', 5);`                                               | `Hello`                         |
| **`right()`**           | Returns the last N characters of a string.                                                                                | `right(string, N)`                                       | `SELECT right('Hello, World!', 6);`                                              | `World!`                        |
| **`split_part()`**      | Splits a string into substrings based on a delimiter and returns the substring at the specified position (1-based index). | `split_part(string, delimiter, position)`                | `SELECT split_part('apple,banana,cherry', ',', 2);`                              | `banana`                        |
| **`split_to_array()`**  | Splits a string into an array of substrings based on a delimiter.                                                         | `split_to_array(string, delimiter)`                      | `SELECT split_to_array('apple,banana,cherry', ',');`                             | `{apple,banana,cherry}`         |
| **`string_to_array()`** | Splits a string into an array of substrings based on a regular expression delimiter.                                      | `string_to_array(string, delimiter)`                     | `SELECT string_to_array('apple banana cherry', '\s');`                           | `{apple,banana,cherry}`         |
